name: エンジニアリングタスク
description: 開発関連のタスクを作成
title: "[Dev]: "
labels: ["engineering"]
body:
  - type: dropdown
    id: category
    attributes:
      label: 開発カテゴリ
      description: タスクの種類を選択してください
      options:
        - 機能実装
        - バグ修正
        - リファクタリング
        - テスト作成
        - 設計・アーキテクチャ
        - パフォーマンス改善
        - セキュリティ対応
        - ドキュメント作成
        - 環境構築
        - 調査・検証
        - レビュー
        - その他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: タスクの優先度を選択してください
      options:
        - Critical（即時対応）
        - High（今週中）
        - Medium（来週中）
        - Low（対応予定）
    validations:
      required: true

  - type: input
    id: related_components
    attributes:
      label: 関連コンポーネント
      description: 関連するコンポーネントやモジュール名
      placeholder: 例：認証システム、ユーザー管理など

  - type: textarea
    id: technical_details
    attributes:
      label: 技術的詳細
      description: 実装の詳細や技術的な要件を記述してください
      placeholder: |
        ### 概要
        
        ### 技術要件
        
        ### 変更範囲
        
        ### 注意点
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 実施事項
      description: 必要な作業項目にチェックを入れてください
      options:
        - label: 設計レビュー
        - label: 実装
        - label: ユニットテスト
        - label: 結合テスト
        - label: ドキュメント更新
        - label: コードレビュー
